name: Update series periodically or upon manual trigger

on:
  workflow_dispatch:

jobs:
  update:
    name: Update series
    runs-on: ubuntu-latest

    steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends jq

    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Checkout twint
      uses: actions/checkout@v3
      with:
        repository: woluxwolu/twint
        path: twint

    - name: Install twint
      run: pip3 install . -r requirements.txt
      working-directory: twint

    - name: Run update script
      run: ./update_series.sh

    - name: Commit changes
      run: |
        git config --global user.name 'catgirl-bot'
        git config --global user.email '<>'
        git add series
        git commit -m "Update index (beep boop)" || exit 0
        git push
